services:
  postgres:
    image: postgres:15-alpine
    container_name: raising-crm-postgres-prod
    environment:
      POSTGRES_USER: raising_user
      POSTGRES_PASSWORD: raising_password
      POSTGRES_DB: raising_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: raising-crm-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}
        - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    container_name: raising-crm-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://raising_user:raising_password@postgres:5432/raising_crm
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data_prod:
  redis_data_prod:
