name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier check
      run: npm run format:check

    - name: Run ESLint with detailed output
      run: npm run lint -- --format=json --output-file=eslint-report.json
      continue-on-error: true

    - name: Upload ESLint report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-report
        path: eslint-report.json

    - name: Run TypeScript strict check
      run: npx tsc --noEmit --strict

    - name: Check bundle size
      run: |
        npm run build
        npx bundlesize
      env:
        DATABASE_URL: "postgresql://user:pass@localhost:5432/test"
        NEXTAUTH_SECRET: "test-secret"
        NEXTAUTH_URL: "http://localhost:3000"

  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for outdated dependencies
      run: npm outdated || true

    - name: Check for unused dependencies
      run: npx depcheck

    - name: License compliance check
      run: npx license-checker --summary
